name: wordpress
services:
  wordpress:
    # image: wordpress:php7.3-fpm
    build:
      context: .
      dockerfile: ./wordpress/dockerfile
    container_name: wp
    volumes:
      - ${DEFAULT_DIR}/wpfiles:/var/www/html
      - ${PHP_DIR}/uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
    environment:
      - VIRTUAL_HOST=${WEB_URL}
      - WORDPRESS_DB_USER=budhilaw
      - WORDPRESS_DB_NAME=budhilaw_blog
      - WORDPRESS_TABLE_PREFIX=bb_
      - WORDPRESS_DB_PASSWORD=1550
      - WORDPRESS_DB_HOST=mariadb
      - MYSQL_PORT_3306_TCP=4306
    depends_on:
      - mariadb
    restart: unless-stopped

  mariadb:
    image: mariadb:latest
    container_name: mariadb
    volumes:
      - ${SQLDATA_DIR}:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=1550
      - MYSQL_DATABASE=budhilaw_blog
      - MYSQL_USER=budhilaw
      - MYSQL_PASSWORD=1550
    restart: unless-stopped
    ports:
      - "4306:3306"

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ${DEFAULT_DIR}/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ${DEFAULT_DIR}/nginx/timeout.conf:/etc/nginx/conf.d/timeout.conf
      - ${DEFAULT_DIR}/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ${DEFAULT_DIR}/logs/nginx:/var/log/nginx
      - ${DEFAULT_DIR}/wpfiles:/var/www/html
      - ${DEFAULT_DIR}/root-ca/mkcert:/etc/ssl
    depends_on:
      - wordpress
    restart: unless-stopped
