version: '3.6'
services:
  wordpress:
    # image: wordpress:php7.3-fpm
    build:
      context: .
      dockerfile: ./wordpress/dockerfile
    container_name: wpcl
    volumes:
      - ${DEFAULT_DIR}/wpcl:/var/www/html
      - ${PHP_DIR}/uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
    environment:
      - VIRTUAL_HOST=cepatlakoo.test
      - WORDPRESS_DB_USER=wpcl
      - WORDPRESS_DB_NAME=cepatlakoo
      - WORDPRESS_TABLE_PREFIX=cl_
      - WORDPRESS_DB_PASSWORD=wpclpass
      - WORDPRESS_DB_HOST=mariadb
      - MYSQL_PORT_3306_TCP=4306
    depends_on:
      - mariadb
    restart: unless-stopped

  mariadb:
    image: mariadb:latest
    container_name: mariadb
    volumes:
      - ${SQLDATA_DIR}:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=toor
      - MYSQL_DATABASE=cepatlakoo
      - MYSQL_USER=wpcl
      - MYSQL_PASSWORD=wpclpass
    restart: unless-stopped
    ports:
      - "4306:3306"

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ${DEFAULT_DIR}/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ${DEFAULT_DIR}/nginx/timeout.conf:/etc/nginx/conf.d/timeout.conf
      - ${DEFAULT_DIR}/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ${DEFAULT_DIR}/logs/nginx:/var/log/nginx
      - ${DEFAULT_DIR}/wpcl:/var/www/html
      - /Users/ericsson/Sites/root-ca/mkcert:/etc/ssl
    depends_on:
      - wordpress
    restart: unless-stopped
