FROM nginx:latest

COPY ./nginx/default.conf /etc/nginx/conf.d/default.conf

RUN cd /usr/local/share/ && \
    go get -u github.com/FiloSottile/mkcert && \
    cd src/github.com/FiloSottile/mkcert && \
    go build -o /bin/mkcert

WORKDIR /root/.local/share/mkcert

EXPOSE 80 443

CMD mkcert -install && for i in $(echo $domain | sed "s/,/ /g"); do mkcert $i; done && tail -f -n0 /etc/hosts